name: Compile All Extensions

on:
  workflow_dispatch:
    inputs:
      max_extensions:
        description: 'Maximum number of extensions to process at once'
        required: false
        default: '200'
        type: string

jobs:
  compile-extensions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Process Extensions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAX_COUNT: ${{ github.event.inputs.max_extensions }}
      run: |
        #!/bin/bash
        set -e

        # Function to trigger workflow for a single extension
        trigger_extension_workflow() {
            local extension_name="$1"
            local php_versions="$2"

            echo "🔍 Processing extension: $extension_name"

            # Check if matrix file exists
            if [ ! -f "extension/BuildPhpExtension/config/matrix.json" ]; then
                echo "❌ Matrix file matrix.json not found"
                return 1
            fi

            # Get repository URL/name
            repo=$(jq -r ".$extension_name.source // empty" "extension/BuildPhpExtension/config/matrix.json")
            if [ -z "$repo" ]; then
                echo "❌ Repository source not found for $extension_name"
                return 1
            fi

            # Process PHP versions
            IFS=',' read -ra php_version_list <<< "$php_versions"
            declare -A ext_groups
            invalid_versions=()

            for php_version in "${php_version_list[@]}"; do
                php_version=$(echo "$php_version" | xargs)
                echo "🔍 Processing PHP version: $php_version"

                ext_version=$(jq -r ".$extension_name.ver.\"$php_version\" // empty" "extension/BuildPhpExtension/config/matrix.json")

                if [ -z "$ext_version" ]; then
                    echo "⚠️ PHP $php_version - version not found"
                    invalid_versions+=("$php_version")
                else
                    echo "✅ PHP $php_version - extension version: $ext_version"

                    if [ -z "${ext_groups[$ext_version]:-}" ]; then
                        ext_groups[$ext_version]="$php_version"
                    else
                        ext_groups[$ext_version]="${ext_groups[$ext_version]},$php_version"
                    fi
                fi
            done

            # Check if we have any valid versions
            if [ ${#ext_groups[@]} -eq 0 ]; then
                echo "❌ No valid PHP versions found for extension $extension_name"
                return 1
            fi

            # Trigger workflow for each extension version
            total_workflows=0
            for ext_version in "${!ext_groups[@]}"; do
                php_versions_for_ext="${ext_groups[$ext_version]}"

                # Determine ts list based on extension name
                if [[ "$extension_name" == *"parallel"* ]]; then
                    ts_list="ts"
                elif [[ "$extension_name" == *"wincache"* ]]; then
                    ts_list="nts"
                else
                    ts_list="nts,ts"
                fi

                echo "🚀 Triggering workflow for extension '$extension_name' version $ext_version and PHP versions: $php_versions_for_ext"

                # Determine parameter name based on source type
                if [[ "$repo" =~ ^https?:// ]]; then
                    param_name="extension-url"
                    param_value="$repo"
                else
                    param_name="extension-name"
                    param_value="$repo"
                fi

                # Trigger the PECL workflow
                curl -sL \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer $GITHUB_TOKEN" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/OSPanel/php-windows-builder/actions/workflows/pecl.yml/dispatches \
                  -d "{
                    \"ref\": \"main\",
                    \"inputs\": {
                      \"$param_name\": \"$param_value\",
                      \"extension-ref\": \"$ext_version\",
                      \"php-version-list\": \"$php_versions_for_ext\",
                      \"arch-list\": \"x64\",
                      \"ts-list\": \"$ts_list\"
                    }
                  }"

                if [ $? -eq 0 ]; then
                    echo "✅ Successfully triggered workflow for $extension_name version $ext_version"
                    ((total_workflows++))
                else
                    echo "❌ Failed to trigger workflow for $extension_name version $ext_version"
                    return 1
                fi

                echo ""
                # Rate limiting
                sleep 2
            done

            if [ ${#invalid_versions[@]} -gt 0 ]; then
                invalid_versions_string=$(IFS=', '; echo "${invalid_versions[*]}")
                echo "⚠️ Warning: The following PHP versions were not found in matrix.json for $extension_name: $invalid_versions_string"
            fi

            echo "✅ Successfully triggered $total_workflows workflows for extension $extension_name"
            return 0
        }

        # Main logic
        matrix_path="extension/BuildPhpExtension/config/matrix.json"
        max_count="${MAX_COUNT:-200}"

        # Validate max_count is a number
        if ! [[ "$max_count" =~ ^[0-9]+$ ]]; then
            echo "❌ max_count must be a positive integer, got: $max_count"
            exit 1
        fi

        # Check if matrix file exists
        if [ ! -f "$matrix_path" ]; then
            echo "❌ Matrix file not found: $matrix_path"
            exit 1
        fi

        # Get list of all extensions
        readarray -t all_extensions < <(jq -r 'keys[]' "$matrix_path")

        if [ ${#all_extensions[@]} -eq 0 ]; then
            echo "❌ No extensions found in matrix file"
            exit 1
        fi

        # Limit to max_count if needed
        to_process=("${all_extensions[@]:0:$max_count}")

        echo "📊 Total extensions in matrix: ${#all_extensions[@]}"
        echo "📊 Extensions to process: ${#to_process[@]}"
        echo "📋 Extension list: ${to_process[*]}"

        # Process extensions
        successfully_processed=()
        failed_extensions=()
        versions="7.2,7.3,7.4,8.0,8.1,8.2,8.3,8.4"

        for extension in "${to_process[@]}"; do
            echo "🔄 Processing extension: $extension"

            if trigger_extension_workflow "$extension" "$versions"; then
                successfully_processed+=("$extension")
                echo "✅ Extension $extension processed successfully"
            else
                failed_extensions+=("$extension")
                echo "❌ Error processing extension $extension"
            fi

            # Rate limiting between extensions
            sleep 3
        done

        echo "✅ Processing completed."
        echo "📊 Successfully processed: ${#successfully_processed[@]}"
        echo "📊 Failed to process: ${#failed_extensions[@]}"

        if [ ${#failed_extensions[@]} -gt 0 ]; then
            echo "❌ Failed extensions: ${failed_extensions[*]}"
        fi

        # Exit with error if all extensions failed
        if [ ${#successfully_processed[@]} -eq 0 ] && [ ${#to_process[@]} -gt 0 ]; then
            echo "❌ All extensions failed to process"
            exit 1
        fi

        echo "🎉 All workflows have been triggered successfully!"